# Generated by Django 5.1.6 on 2025-02-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_it", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("name_it", models.CharField(max_length=100)),
                ("cost", models.FloatField()),
                ("labels", models.JSONField(blank=True, null=True)),
                ("labels_it", models.JSONField(blank=True, null=True)),
                ("short_description", models.TextField()),
                ("short_description_it", models.TextField()),
                ("description", models.TextField()),
                ("description_it", models.TextField()),
                ("rating", models.FloatField()),
                ("clicks", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("revenue", models.IntegerField(default=0)),
                ("purchased", models.IntegerField(default=0)),
                ("affiliate_link", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="website.category"
                    ),
                ),
                ("see_also", models.ManyToManyField(blank=True, to="website.product")),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField()),
                ("feedback", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/images/%Y/%m/%d"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.product",
                    ),
                ),
            ],
        ),
    ]
